### ISSUE TITLE
compiling takes a while

### ISSUE THREAD

**Issue by CoderMonkies** [datatypevoid/ng2-mean-webpack#1]
```
> ng2-mean-webpack@0.0.0 start C:\ng2Mean
> gulp
[17:50:39] Using gulpfile C:\ng2Mean\gulpfile.js
[17:50:39] Starting 'clean:docs'...
[17:50:39] Starting 'serve:watch'...
[17:50:39] Finished 'serve:watch' after 3.1 ms
[17:50:39] Starting 'watch:docs'...
[17:53:25] Finished 'watch:docs' after 2.77 min
[17:53:25] Starting 'watch:sass'...
[17:54:36] Finished 'watch:sass' after 1.18 min
[17:54:36] Finished 'clean:docs' after 3.95 min
[17:54:36] Starting 'default'...
[17:54:36] Finished 'default' after 19 μs
[17:54:36] [nodemon] 1.8.1
[17:54:36] [nodemon] to restart at any time, enter `rs`
[17:54:36] [nodemon] watching: *.*
[17:54:36] [nodemon] starting `node server.js`
Node environment set for development
No value set for MONGO_URI...
Using the supplied value from config object...
MONGO_URI set for development
Wizardry is afoot on port 8080
Successfully connected to development database on startup
GET / 304 13.088 ms - -
```

**Comment by datatypevoid** [comment]
What you can do is just run each of those commands in a separate console window since the don't run in async. There isn't much I can do as this is due to the modules used for each of those tasks.

**Comment by datatypevoid** [comment]
Commit ec7deed reintroduces hot reloading to the framework and makes the automatic documentation generation and `sass` linting provided by `gulp` optional to run in a second terminal, rather than bogging down slower hardware. I hope this alleviates any inconveniences!

**Comment by datatypevoid** [comment]
The fix from commit ec7deed was insufficient to fix the problem with hot reloading as I was not understanding fully how the Webpack dev server integrates with everything. Commit 4282d44 uses a Webpack proxy in order to allow the front-end to properly communicate with the back-end. The fix you used in your personal branch masked the problem as long as you didn't try to use the back-end at all, as you would when accessing an API or something of the like. Everything seems to be working as intended now.

**Comment by datatypevoid** [comment]
![ng2-mean-webpack-head](https://cloud.githubusercontent.com/assets/10481547/13731958/a49e5798-e94c-11e5-863f-d2f8a99af71a.png)

**Comment by datatypevoid** [comment]
![ng2-mean-webpack-head](https://cloud.githubusercontent.com/assets/10481547/13731985/54632e74-e94d-11e5-80cf-8d6f24516b7b.png)

**Comment by datatypevoid** [comment]
![ng2-mean-webpack-head](https://cloud.githubusercontent.com/assets/10481547/13731995/9080e6ee-e94d-11e5-9280-ab98e0bc7436.png)

**Comment by datatypevoid** [comment]
![ng2-mean-webpack-head-branded](https://cloud.githubusercontent.com/assets/10481547/13732046/5ba42ab0-e94f-11e5-9962-ab04cbd6779f.png)
