### ISSUE TITLE
Failed at the vulgar@2.0.4 server:dev script 'webpack-dev-server --inline --progress --profile --colors --watch --display-error-details --display-cached  --content-base src/'.

### ISSUE THREAD

**Issue by ghost** [datatypevoid/ng2-mean-webpack#13]
**Note: for support questions, please use one of these channels:** [Chat: VulgarDisplayOf2^2.slack](http://www.davidniciforovic.com/wp-login.php?action=slack-invitation) or [Twitter: @datatype_void](https://twitter.com/datatype_void)
- *_I'm submitting a ... *_
  
  [x] bug report
  
  [ ] feature request
  
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
- **What is the current behavior?**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
- https://plnkr.co, https://codepen.io, or similar.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by datatypevoid** [comment]
Hey there! Glad to see your interest in the project, however this repo is deprecated by [vulgar](https://github.com/datatypevoid/vulgar). Please note that I am actively bringing the project up to date with the Angular 2 release, but the `development` branch is the most up to date stable branch.
