### ISSUE TITLE
typings.json out of date, throwing 404s

### ISSUE THREAD

**Issue by mike-robertson** [datatypevoid/ng2-mean-webpack#2]
The typings.json is out of date. I copied the file used in the angular2-webpack-starter project and that fixed any 404s that were being thrown from changed github urls. I think that the only things that changed were es6-promise, jasmine, and zone.js. Here is the updated file though in case I missed any:

`{
  "dependencies": {
    "es6-promise": "github:typed-typings/npm-es6-promise#fb04188767acfec1defd054fc8024fafa5cd4de7"
  },
  "devDependencies": {},
  "ambientDependencies": {
    "angular-protractor": "github:DefinitelyTyped/DefinitelyTyped/angular-protractor/angular-protractor.d.ts#64b25f63f0ec821040a5d3e049a976865062ed9d",
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#6697d6f7dadbf5773cb40ecda35a76027e0783b2",
    "hammerjs": "github:DefinitelyTyped/DefinitelyTyped/hammerjs/hammerjs.d.ts#74a4dfc1bc2dfadec47b8aae953b28546cb9c6b7",
    "jasmine": "github:DefinitelyTyped/DefinitelyTyped/jasmine/jasmine.d.ts#4b36b94d5910aa8a4d20bdcd5bd1f9ae6ad18d3c",
    "ng2": "github:gdi2290/typings-ng2/ng2.d.ts#32998ff5584c0eab0cd9dc7704abb1c5c450701c",
    "node": "github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#8cf8164641be73e8f1e652c2a5b967c7210b6729",
    "selenium-webdriver": "github:DefinitelyTyped/DefinitelyTyped/selenium-webdriver/selenium-webdriver.d.ts#a83677ed13add14c2ab06c7325d182d0ba2784ea",
    "webpack": "github:DefinitelyTyped/DefinitelyTyped/webpack/webpack.d.ts#95c02169ba8fa58ac1092422efbd2e3174a206f4",
    "zone.js": "github:DefinitelyTyped/DefinitelyTyped/zone.js/zone.js.d.ts#c393f8974d44840a6c9cc6d5b5c0188a8f05143d"
  }
}
`

**Comment by datatypevoid** [comment]
Yeah I have it fixed in the local version. The urls broke a couple of days after I posted this project. I've been preoccupied in meatspace, but I have a lot of updates coming up with the end of the week, maybe into the weekend. Thanks for the feedback.

**Comment by datatypevoid** [comment]
Sorry for taking so long to address this, but I am glad to see that you got it working for yourself. Commit 97766bd address the references for the typings that you have pointed out, Thanks again @mike-robertson!
