### ISSUE TITLE
no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by Perezmarc** [datatypevoid/ng2-mean-webpack#4]
Hello!
Great product, we talked on twitter...

I've followed the getting started instructions, and when executing gulp serve I got this error:
path.js:1158
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1158:25)
    at startup (node.js:98:32)
    at node.js:933:3

Thanks!

**Comment by datatypevoid** [comment]
Thanks again man! Would you mind telling me which `OS`, `npm` and `node` you are using to start? Let's get this ironed out!

**Comment by Perezmarc** [comment]
Mac OS el capitan 10.11.3 
npm 3.7.5
node 5.7.0

**Comment by datatypevoid** [comment]
Alright, I will look into it right after my lunch break. I have to boot the Mac up to see if it throws it for me with the latest version of the repo. Let me know if you uncover anything on your end.

**Comment by datatypevoid** [comment]
For now instead of using `gulp serve`, just use `node server` and you will just have to reload the server anytime you change the back-end code until I figure out why this error is being thrown.

**Comment by Perezmarc** [comment]
Its everything working now, I had to properly configure de config.json, I had a mistake, but also had to delete comments... weird though.

**Comment by datatypevoid** [comment]
@Perezmarc Thanks for the update. `Json` doesn't allow for comments like I have in the tutorial, I'll update it with a note of that. Thanks again!
