### ISSUE TITLE
Duplicate identifier 'Zone'.

### ISSUE THREAD

**Issue by Perezmarc** [datatypevoid/ng2-mean-webpack#5]
I'm getting a bunch of errors when executing npm start.

`default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/selenium-webdriver/selenium-webdriver.d.ts (5390,5):
    Duplicate identifier 'export='.
[default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/selenium-webdriver/selenium-webdriver.d.ts (5394,5):
    Duplicate identifier 'export='.
[default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/webpack/index.d.ts (264,5):
    Duplicate identifier 'export='.
[default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/webpack/webpack.d.ts (264,5):
    Duplicate identifier 'export='.
[default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/zone/index.d.ts (9,15):
    Duplicate identifier 'Zone'.
[default] /Users/marcperez/Relive/develop/ng2-mean-webpack/typings/browser/ambient/zone/zone.d.ts (9,15):
    Duplicate identifier 'Zone'.`

I believe I'm missing some excludes in tsconfig.json, could it be?
tsconfig:
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "exclude": [
    "node_modules",
    "typings/main.d.ts",
    "typings/main"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "!./node_modules/**/*.ts",
    "src/custom-typings.d.ts",
    "typings/browser.d.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useCache": true,
    "resolveGlobs": true,
    "forkChecker": true,
    "cacheDirectory": "node_modules/.awesome-typescript-loader-cache"
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}
`

**Comment by datatypevoid** [comment]
Hey there @Perezmarc ! No that is not what this error is indicating. Just give me a minute to get a fresh build to see what the typings files are looking like with the latest build. Meanwhile, have you followed all of the initial installation instructions and ran `npm run build` once before trying `npm start` as the `README` indicates?

**Comment by Perezmarc** [comment]
I followed getting started instructions here on git

**Comment by datatypevoid** [comment]
Alright, I am just waiting for all of the dependencies to install.

**Comment by datatypevoid** [comment]
Are you building the initial repo or have you made modifications?

**Comment by Perezmarc** [comment]
building inital repo, no modifications so far

**Comment by datatypevoid** [comment]
@Perezmarc Hmm a fresh clone of the repo gives me no problems. Could you show me what the `typings.json` file contains and possibly try a fresh clone and perform these steps on it?

``` bash
# clone our repo
# --depth 1 removes all but one .git commit history
git clone --depth 1 https://github.com/datatypevoid/ng2-mean-webpack.git

# change directory to our repo
cd ng2-mean-webpack

# add required global libraries
 npm install typings webpack-dev-server -g

# install the repo with npm
npm install

# create configuration json file for env vars
# save in `config/` as `config.json`
{
  "ENV" : "development",
  "PORT" : 3000,
  "MONGO_URI" : {
    "DEVELOPMENT" : "mongodb://[username:password]@host[:port]",
    "PRODUCTION" : "mongodb://[username:password]@host[:port]",
    "TEST" : "mongodb://[username:password]@host[:port]"
  },
  "SESSION_SECRET" : "355FC4FE9348639B4E4FED1B8E93C"
}

# build code
npm run build

# start up the stack

# this command runs two commands in parallel via `concurrently`:
# `npm run server` starts up `webpack-dev-server` allowing for
# hot module reloading
# `npm` run watch` uses `webpack` to watch the necessary files
# and build on file change
npm start

# in a separate terminal:
# start `Express` server
gulp serve
```

**Comment by Perezmarc** [comment]
I did it once again I no errors this time :S
Thanks again!

**Comment by datatypevoid** [comment]
No problem! I am glad it worked for you. I have seen the same error a few times myself when I was building the framework, so I thought it might be that.
