### ISSUE TITLE
What is the proper way of using template files?

### ISSUE THREAD

**Issue by Perezmarc** [datatypevoid/ng2-mean-webpack#6]
I want to use template files, indexing in component such as templateUrl.

if I use template attribute I get no errors, but if I use templateUrl and redirect it I do...

My server finds the template, 200 response. 
## **The error**

```
EXCEPTION: Template parse errors:
Unexpected closing tag "head" ("
  <base href="/">

[ERROR ->]</head>

<body>
"): HeaderComponent@36:0
Unexpected closing tag "html" ("

<script src="polyfills.bundle.js"></script><script src="main.bundle.js"></script></body>
[ERROR ->]</html>
"): HeaderComponent@61:0
```
## **The component**

```
import {Component} from 'angular2/core';

@Component({
    selector: 'my-header',
    templateUrl: 'src/app/common/header.tpl.html'
})

export class HeaderComponent {

}
```
## **The app component**

```
import {NgFor} from 'angular2/common';
import {Todo} from './components/todo/todo.component';
import {HeaderComponent} from "./common/header.component";

/*
 * App Component
 * Top Level Component
 */
@Component({
    selector: 'app',
    providers: [],
    directives: [ ...ROUTER_DIRECTIVES, Todo, NgFor, HeaderComponent ],
    pipes: [],
    // Load our main `Sass` file into our `app` `component`
    styleUrls: [require("!style!css!sass!../sass/main.scss")],
    template: `
    <my-header></my-header>
    <main>
      <router-outlet></router-outlet>
    </main>
  `
})

@RouteConfig([
    { path: '/', component: Todo, name: 'Index' }
])

export class App {
    constructor() {

    }
}
```

Thanks a lot, again!

**Comment by datatypevoid** [comment]
Good morning @Perezmarc ! One thing I noticed with the code you posted:

Your `templateUrl` for the custom `header` component is setup like this:

``` bash
templateUrl: 'src/app/common/header.tpl.html'
```

Instead of the absolute url here try using a relative url like:

``` bash
templateUrl: './header.tpl.html'
```

Let me know if this helps!

**Comment by Perezmarc** [comment]
Hi!
nope, that's not the mistake. I had it as you say before, and I reversed back now and still the same error... 
Probably is something related to angular2 itself, not your framework, I was just wondering what could it be... 
:S

**Comment by datatypevoid** [comment]
Could you try `template: require('./header.tpl.html')` instead of `templateUrl: './header.tpl.html'` ?

**Comment by datatypevoid** [comment]
I have `templateUrl` working for the `home` component, so I have to look into this a bit if that doesn't work.

**Comment by datatypevoid** [comment]
I also found this: https://github.com/angular/angular/issues/7295

**Comment by datatypevoid** [comment]
It could be related but I am not sure yet.

**Comment by datatypevoid** [comment]
Actually that is how I do it in the `home` component hehe.

**Comment by Perezmarc** [comment]
oops I forgot you had the home since you made me delete the app folder in the post hehe.
I'll have a look and tell you what was wrong

**Comment by Perezmarc** [comment]
Ok, got it working using :
 template: require('./header.tpl.html')
instead of
 templateUrl: './header.tpl.html'

Why is templateUrl not working? I've developed some things in ng2 and used templateUrl, is it because of webpack?

**Comment by datatypevoid** [comment]
It has to do with how `Webpack` bundles its files. You could technically use the `CopyWebpackPlugin` in `webpack.config.js` to move/copy the file to the appropriate folder. You can see an example of this around `line 98` in webpack.config.js`. This would allow you to use`TemplateURL`as you were doing. The thing about`TemplateURL`that I forgot is that it doesn't allow relative URLs, which`require`does. Basically, using`require` just cuts down the amount of code we have to write to accomplish the same thing, in this case.
