### ISSUE TITLE
Collaborate with mean.js?

### ISSUE THREAD

**Issue by simison** [datatypevoid/ng2-mean-webpack#7]
Hi! Cool project.

Have you thought of contributing to @meanjs instead? It's a vibrant, active and very popular MEAN boilerplate currently in Angular 1.

**Comment by datatypevoid** [comment]
I have heard of @meanjs but the team and I who use this framework can't afford to wait for them to catch up with the times. This framework is a future-now project that doesn't have to be bound by the conventions of `ES5` or `Angular 1.x`. Not to mention a personal testing grounds for my own projects. I started this so I had a framework that works the way that I want and need it to, and if others decide they like the way I do things, they are more then welcome to join the effort and hammer this out with me. I am a tinkerer at the end of the day, what can I say? ;)

**Comment by simison** [comment]
Fair enough. :-) Cheers!
