### ISSUE TITLE
express sendfile depreciated. 

### ISSUE THREAD

**Issue by liu-kanghui** [datatypevoid/ng2-mean-webpack#9]
express deprecated res.sendfile: Use res.sendFile instead app/routes.js:73:9

I am trying to replace the template in app.ts  using an external app.html
but when i use sendFile. 
it throws me error like this 

TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/Users/kanghuiliu/goodi-beta9/node_modules/express/lib/response.js:403:11)
    at routes.js:81:9
    at Layer.handle [as handle_request](/Users/kanghuiliu/goodi-beta9/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kanghuiliu/goodi-beta9/node_modules/express/lib/router/route.js:131:13)

**Comment by liu-kanghui** [comment]
Ohhh

I added  in routes.js 

import path from 'path"
res.sendFile(path.join(__dirname, '../dist', 'index.html'));

then it words    :)))

**Comment by datatypevoid** [comment]
Glad you got everything worked out @liu-kanghui !

I will have that `Express` error fixed very soon, I just can't seem to get around to it ;p

Just so you know, the project has switched names and continued at: https://github.com/datatypevoid/vulgar

Also, if you have support questions that aren't necessarily issues, we do have a support Slack that you can access here: http://www.davidniciforovic.com/wp-login.php?action=slack-invitation

Hope everything else is working out well for you!
